<?php
/**
 * @file
 */

include_once 'newspaper_solr.features.inc';

/**
 * Implements hook_apachesolr_query_prepare().
 */
function newspaper_solr_apachesolr_query_prepare(DrupalSolrQueryInterface $query) {
  // Alter available sorts.
  $sorts = $query->getAvailableSorts();
  $sorts = array(
    'score' => array('title' => t('Relevance')) + $sorts['score'],
    'ds_created' => $sorts['ds_created'],
  );
  $query->setAvailableSorts($sorts);

  $gap = $query->getParam('f.ds_created.facet.date.gap');
  if ($gap[0] == '+1' . FACETAPI_DATE_YEAR) {
    $query->removeParam('f.ds_created.facet.date.gap');
    $query->addParam('f.ds_created.facet.date.gap', '+1' . FACETAPI_DATE_MONTH);
  }
}

/**
 * Implements hook_facetapi_facet_info_alter().
 */
function newspaper_solr_facetapi_facet_info_alter(&$facets) {
  // Alter created facet to always show months.
  if (isset($facets['created'])) {
    $facets['created']['map callback'] = 'newspaper_solr_created_facet_map';
  }
}

/**
 * Map callback for created date facet.
 *
 * Always show months for created facet, instead of the default of showing just
 * years first then months.
 */
function newspaper_solr_created_facet_map($values, $options) {
  if (empty($options['format callback'])) {
    $options['format callback'] = 'facetapi_format_timestamp';
  }
  $map = array();
  foreach ($values as $value) {
    $range = explode(' TO ', trim($value, '{[]}'));
    if (isset($range[1])) {
      $map[$value] = facetapi_format_date($range[0], FACETAPI_DATE_MONTH, $options['format callback']);
    }
  }
  return $map;
}
